### ISSUE TITLE
Failure on running indexer

### ISSUE THREAD

**Issue by chad-iris** [nick-iris/obspy#6]
With `tsindex` branch checked out, I ran `pip install -v -e .` for a testing environment.

```
~/src/obspy-nick-iris$ ls -l data
total 1544272
-rw-r--r--  1 chad  staff  790664704 Sep 13 11:57 2010.ANMO.LH.mseed
~/src/obspy-nick-iris$ ipython
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from obspy.clients.filesystem.tsindex import Indexer

In [2]: idx = Indexer("data")
[2018-09-13 12:59:10,014] - obspy.clients.filesystem.tsindex - WARNING: No sqlite3 database file exists at `/Users/chad/src/obspy-nick-iris/timeseries.sqlite`.
[2018-09-13 12:59:10,022] - obspy.clients.filesystem.tsindex - WARNING: Leap seconds file `/Users/chad/src/obspy-nick-iris/leap-seconds.list` not found. No leap seconds file will be used for indexing.

In [3]: idx.build_file_list()
Out[3]: ['/Users/chad/src/obspy-nick-iris/data/2010.ANMO.LH.mseed']

In [4]: idx.run()
mseedindex version: 2.7
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/chad/src/obspy-nick-iris/obspy/clients/filesystem/tsindex.py", line 1186, in _run_index_command
    for option, value in bulk_params.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chad/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/chad/src/obspy-nick-iris/obspy/clients/filesystem/tsindex.py", line 1202, in _run_index_command
    raise OSError(msg)
OSError: Error running command `mseedindex` - 'dict' object has no attribute 'iteritems'
"""

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
<ipython-input-4-6ca75811840a> in <module>()
----> 1 idx.run()

~/src/obspy-nick-iris/obspy/clients/filesystem/tsindex.py in run(self, build_summary, relative_paths, reindex)
   1010             # Also need get to raise the exceptions workers may throw.
   1011             for proc in proccesses:
-> 1012                 cmd, rc, out, err = proc.get(timeout=999999)
   1013                 if rc:
   1014                     logger.warning("FAIL [{0}] '{1}' out: '{2}' err: '{3}'"

~/miniconda3/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

OSError: Error running command `mseedindex` - 'dict' object has no attribute 'iteritems'

In [5]: 
```

**Comment by nick-iris** [comment]
Sorry about that. This was caused by a Python 3 compatibility problem. It should now be fixed.

**Python 2 Example:**
```
In [1]: from obspy.clients.filesystem.tsindex import Indexer
/Users/nick/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [2]: idx = Indexer("/Users/nick/data")
[2018-09-13 13:57:13,103] - obspy.clients.filesystem.tsindex - WARNING: Leap seconds file `/Users/nick/Development/workspace/obspy/leap-seconds.list` not found. No leap seconds file will be used for indexing.

In [3]: idx.run(reindex=True)
mseedindex version: 2.7.1

In [4]: from obspy.clients.filesystem.tsindex import Client

In [5]: client = Client("timeseries.sqlite")

In [6]: client.get_nslc()
Out[6]: 
[(u'CU', u'TGUH', u'00', u'BHZ'),
 (u'KO', u'KARS', u'', u'HHE'),
 (u'KO', u'KARS', u'', u'HHN'),
 (u'KO', u'KARS', u'', u'HHZ')]

In [7]: stream = client.get_waveforms_bulk(client.get_availability_extent())

In [8]: print(stream)
32 Trace(s) in Stream:

KO.KARS..HHN | 2018-05-23T23:59:56.150000Z - 2018-05-24T03:03:41.990000Z | 100.0 Hz, 1102585 samples
...
(30 other traces)
...
KO.KARS..HHZ | 2018-05-24T05:43:09.990000Z - 2018-05-25T00:00:03.850000Z | 100.0 Hz, 6581387 samples

[Use "print(Stream.__str__(extended=True))" to print all Traces]
```

**Python 3 Example:**

```
| => python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from obspy.clients.filesystem.tsindex import Indexer
>>> idx = Indexer("/Users/nick/data")
[2018-09-13 14:04:27,613] - obspy.clients.filesystem.tsindex - WARNING: Leap seconds file `/Users/nick/Development/workspace/obspy/leap-seconds.list` not found. No leap seconds file will be used for indexing.
>>> idx.run(reindex=True)
mseedindex version: 2.7.1
>>> from obspy.clients.filesystem.tsindex import Client
>>> client = Client("timeseries.sqlite")
>>> client.get_nslc()
[('CU', 'TGUH', '00', 'BHZ'), ('KO', 'KARS', '', 'HHE'), ('KO', 'KARS', '', 'HHN'), ('KO', 'KARS', '', 'HHZ')]
>>> stream = client.get_waveforms_bulk(client.get_availability_extent())
>>> print(stream)
32 Trace(s) in Stream:

CU.TGUH.00.BHZ | 2018-01-01T00:00:00.000000Z - 2018-01-01T00:01:00.000000Z | 40.0 Hz, 2401 samples
...
(30 other traces)
...
KO.KARS..HHZ | 2018-05-24T05:43:09.990000Z - 2018-05-25T00:00:03.850000Z | 100.0 Hz, 6581387 samples

[Use "print(Stream.__str__(extended=True))" to print all Traces]
```
